CREATE DATABASE FPL_DAOTAO
USE FPL_DAOTAO
USE master
GO
--------------------------
DROP DATABASE FPL_DAOTAO
DROP TABLE USERS
DROP TABLE GRADE
DROP TABLE STUDENTS
-------------------------
CREATE TABLE USERS
(
USERID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
USERNAME VARCHAR(50) DEFAULT NULL,
USERPASS VARCHAR(50) DEFAULT NULL,
PERMISSION INT DEFAULT NULL 
)
-------------------------
CREATE TABLE STUDENTS
(
STUDENTID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
COUNTLIST INT IDENTITY,
MASV VARCHAR(50) UNIQUE DEFAULT NULL,
HOTEN NVARCHAR(50) DEFAULT NULL,
EMAIL VARCHAR(50) DEFAULT NULL,
SODT VARCHAR(15) DEFAULT NULL,
GIOITINH INT DEFAULT NULL,
DIACHI NVARCHAR(50) DEFAULT NULL,
AVATAR IMAGE DEFAULT NULL
)
--------------------------
CREATE TABLE GRADE
(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
COUNTLIST INT IDENTITY,
STUDENTID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES DBO.STUDENTS(STUDENTID),
TIENGANH VARCHAR(5) DEFAULT NULL,
TINHOC VARCHAR(5) DEFAULT NULL,
GDTC VARCHAR(5) DEFAULT NULL
)
--------------------------
---PhaKeData
INSERT INTO dbo.USERS
VALUES
(DEFAULT,'cauvongsociu1','yeuemHien123',1),
(DEFAULT,'cauvongsociu2','yeuemHien123',2)
----------------------
INSERT INTO dbo.STUDENTS
VALUES
('B82380BF-1F62-4C5B-877E-23FA18DB47C8','SV1',N'Hoàng Thùy Linh','thuylinhhoang@gmail.com.vn','09699676231',1,N'Hải Phòng',(SELECT * FROM OPENROWSET(BULK 'D:\img\1.jpg', SINGLE_BLOB) AS IMG)),
('0837AB06-73C9-4E31-996F-398246553207','SV2',N'Thái Linh Hương','huongak47@gmail.com.vn','09123546321',0,N'Hà Nam',(SELECT * FROM OPENROWSET(BULK 'D:\img\2.jpg', SINGLE_BLOB) AS IMG)),
('1B119DC5-9F9E-4436-8F99-89EEBD66F659','SV3',N'Mèo No Hope','mewmew69@gmail.com.vn','01234429641',1,N'Thái Bình',(SELECT * FROM OPENROWSET(BULK 'D:\img\3.jpg', SINGLE_BLOB) AS IMG)),
('EB46A354-A6F7-4A05-8C02-8B2E2FA14BE8','SV4',N'Phạm Băng Băng','chingchong@gmail.com.vn','01312455761',0,N'Ching Chong',(SELECT * FROM OPENROWSET(BULK 'D:\img\4.jpg', SINGLE_BLOB) AS IMG))
------------------------
INSERT INTO dbo.GRADE
VALUES
(DEFAULT,'B82380BF-1F62-4C5B-877E-23FA18DB47C8','8','9.5','9'),
(DEFAULT,'0837AB06-73C9-4E31-996F-398246553207','5','7.6','9'),
(DEFAULT,'1B119DC5-9F9E-4436-8F99-89EEBD66F659','8.2','4','6'),
(DEFAULT,'EB46A354-A6F7-4A05-8C02-8B2E2FA14BE8','8','10','7.5')

----------------------
GO
CREATE PROC GETDATASTUDENT
AS
BEGIN
SELECT MASV,HOTEN,EMAIL,SODT,GIOITINH,DIACHI,AVATAR FROM DBO.STUDENTS ORDER BY COUNTLIST ASC
END
------------------------
GO
CREATE PROC GETDATAGRADE
AS
BEGIN
SELECT dbo.STUDENTS.MASV,dbo.STUDENTS.HOTEN, dbo.GRADE.TIENGANH,dbo.GRADE.TINHOC,dbo.GRADE.GDTC FROM DBO.GRADE JOIN dbo.STUDENTS ON STUDENTS.STUDENTID = GRADE.STUDENTID ORDER BY dbo.GRADE.COUNTLIST ASC
END
-------------------------
GO
CREATE PROC GETTOP3DATAGRADE
AS
BEGIN
SELECT TOP 3 dbo.STUDENTS.MASV,dbo.STUDENTS.HOTEN, dbo.GRADE.TIENGANH,dbo.GRADE.TINHOC,dbo.GRADE.GDTC FROM DBO.GRADE JOIN dbo.STUDENTS ON STUDENTS.STUDENTID = GRADE.STUDENTID 
ORDER BY (CAST(TIENGANH AS FLOAT)+CAST(TINHOC AS FLOAT)+CAST(GDTC AS FLOAT))/3 DESC
END
---------------------------
GO
CREATE PROC addNewGrade(@STUDENTID VARCHAR(50),@TIENGANH VARCHAR(50),@TINHOC VARCHAR(50),@GDTC VARCHAR(50))
AS
BEGIN
    INSERT INTO dbo.GRADE
    VALUES
    (DEFAULT,@STUDENTID,@TIENGANH,@TINHOC,@GDTC)
END
---------------------------
GO
CREATE PROC DELETE_GRADE(@STUDENTID VARCHAR(50))
AS
BEGIN
DECLARE @ID UNIQUEIDENTIFIER = (SELECT DBO.STUDENTS.STUDENTID FROM DBO.STUDENTS WHERE MASV=@STUDENTID)
DELETE DBO.GRADE
WHERE STUDENTID =@ID
END
--------------------------
GO
CREATE PROC REMAKEGRADE(@STUDENTID VARCHAR(50),@TIENGANH VARCHAR(50),@TINHOC VARCHAR(50),@GDTC VARCHAR(50))
AS
BEGIN
DECLARE @ID UNIQUEIDENTIFIER = (SELECT DBO.STUDENTS.STUDENTID FROM DBO.STUDENTS WHERE MASV=@STUDENTID)
UPDATE DBO.GRADE
SET TIENGANH = @TIENGANH,
TINHOC =@TINHOC,
GDTC=@GDTC
WHERE STUDENTID =@ID
END
--------------------------
GO
CREATE PROC DELETESTUDENT(@MASV VARCHAR(50))
AS
BEGIN
DECLARE @STUDENTID UNIQUEIDENTIFIER = (SELECT STUDENTS.STUDENTID FROM STUDENTS WHERE MASV=@MASV)
DELETE FROM DBO.GRADE
WHERE STUDENTID =@STUDENTID
DELETE FROM STUDENTS
WHERE STUDENTID=@STUDENTID
END
-----------------------------
GO
CREATE PROC GETEVERYSSTUDENTID
AS
BEGIN
SELECT STUDENTS.MASV FROM students
END
--------------------------------
GO
CREATE PROC REMAKESTUDENT(@MASV VARCHAR(50),@HOTEN NVARCHAR(50),@EMAIL VARCHAR(50),@SODT VARCHAR(50),@GIOITINH VARCHAR(2),@DIACHI NVARCHAR(50),@AVATAR NVARCHAR(MAX))
AS
BEGIN
UPDATE DBO.STUDENTS
SET HOTEN = @HOTEN,
EMAIL =@EMAIL,
SODT=@SODT,
GIOITINH=CAST(@GIOITINH AS INT),
DIACHI =@DIACHI
WHERE MASV =@MASV
IF(@AVATAR ='NULL')
BEGIN
RETURN
END
ELSE
BEGIN
DECLARE @IMGRESULT NVARCHAR(MAX)= CONCAT(CHAR(39),@AVATAR,CHAR(39))
DECLARE @ID NVARCHAR(MAX)= CONCAT(CHAR(39),@MASV,CHAR(39))
DECLARE @IMG NVARCHAR(MAX) = 'UPDATE DBO.STUDENTS SET AVATAR = (SELECT * FROM OPENROWSET(BULK '+ @IMGRESULT+ ', SINGLE_BLOB) AS IMG) WHERE MASV =' + @ID
EXEC(@IMG)
END
END
-----------------------------------
GO
CREATE PROC ADDNEWSTUDENT(@MASV VARCHAR(50),@HOTEN NVARCHAR(50),@EMAIL VARCHAR(50),@SODT VARCHAR(50),@GIOITINH VARCHAR(2),@DIACHI NVARCHAR(50),@AVATAR NVARCHAR(MAX))
AS
BEGIN
INSERT INTO DBO.STUDENTS
VALUES
(DEFAULT,@MASV,@HOTEN,@EMAIL,@SODT,CAST(@GIOITINH AS INT),@DIACHI,DEFAULT)
DECLARE @IMGRESULT NVARCHAR(MAX)= CONCAT(CHAR(39),@AVATAR,CHAR(39))
DECLARE @ID NVARCHAR(MAX)= CONCAT(CHAR(39),@MASV,CHAR(39))
DECLARE @IMG NVARCHAR(MAX) = 'UPDATE DBO.STUDENTS SET AVATAR = (SELECT * FROM OPENROWSET(BULK '+ @IMGRESULT+ ', SINGLE_BLOB) AS IMG) WHERE MASV =' + @ID
EXEC(@IMG)
END

SELECT * FROM dbo.STUDENTS
select * from grade